[package]
name = "include_sass"
version = "0.12.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.103", default-features = false }
compiler = { path = "../compiler" }
quote = { version = "1.0.23", default-features = false }

[features]
nightly = []
