[package]
name = "include_sass"
version = "0.12.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.103", default-features = false }
grass_internal = { path = "../grass_internal" }
quote = "1.0.23"

[features]
nightly = []
